### ISSUE TITLE
Tabbing out

### ISSUE THREAD

**Issue by Cborek** [thawkin3/crossyBlock#1]
If the player 'tabs out' or is forced to by the opening or another application or notification, the game does not pause or stop the players' movement. Which will inevitably lead to a death.

Failed Test Case: Player is not locked into one state i.e. constantly moving in one direction (CB-8)

**Comment by thawkin3** [comment]
@Cborek Thanks for logging this. This seems like the expected behavior to me. If you tab away, then the document no longer has focus, so the keypresses won't be registered. For example, if I hit tab once, it takes me to the browser's address bar, so now the focus is there. So that I think would be normal behavior that shouldn't be changed.

One thing I noticed, if I'm holding an arrow key and then I hit the tab key, then the document loses focus (as expected) but when I release my arrow key the player doesn't stop since the document doesn't have focus anymore (makes sense, but isn't great behavior). So maybe that's what you're reporting?

If that's the case, then maybe it would make sense to add a listener for any other keypress and stop the player's movement when that happens. I can do that.

Let me know if I'm misunderstanding anything.

**Comment by Cborek** [comment]
@thawkin3 Yes, that's what I had meant when I first reported the issue. I apologize for not making that clear. I was thinking that if the game would pause when the document loses focus then that might end up working well. Then the player could simply resume play if there's something like an accidental key press or a notification interrupting the gameplay.

**Comment by Cborek** [comment]
@thawkin3 I've also found another issue that is similar to the one that we've been discussing. If you click onto another tab while playing the game itself will 'pause' however the timer will continue counting. So you could essentially just leave the game like that for a very long period of time and build up a massive score using that method.

**Comment by thawkin3** [comment]
@Cborek Good point. I've taken a suggestion from this issue (https://github.com/thawkin3/crossyBlock/issues/5) to calculate the score based on the number of lines of obstacles you pass instead of just time, so that should solve this issue. Thanks!
https://github.com/thawkin3/crossyBlock/pull/6
