### ISSUE TITLE
Code Manipulation

### ISSUE THREAD

**Issue by Bboy111444** [thawkin3/crossyBlock#2]
@thawkin3 If a user hits F12 they can access the source code for the game. This access can lead to the game's manipulation and can violate a few Test Cases such as score manipulation, removal of obstacles, changing player size so it can avoid collisions and other issues. If there were a way to mitigate source code manipulation it would solve these various Test Cases from being violated. 

Failed Test Case: Score should start at 0 (CB-11)
Failed Test Case: Enemies vary in length, but not in width (CB-32)
Failed Test Case: Enemies 'kill' player on contact (CB-33)
Failed Test Case: Enemies vary in speed (CB-34)

**Comment by TheOGBuhay** [comment]
For this Issue I suggest minifying your code. I noticed that in other games you minified, but not in this one. Might help stop this issue.

**Comment by thawkin3** [comment]
@Bboy111444 Thanks for logging this, and thanks @TheOGBuhay for the suggestion. I was able to manipulate the code like you suggested a user could by opening up the developer tools and then entering the following into the console: `angular.element('#gameDiv').scope().score = 100`. This changes the starting score to 100, and then when I start playing the game it keeps counting from 100. So you can easily inflate your score this way.

Minifying the code is generally a good idea for production apps, so that's a good suggestion. I hadn't minified this code since it was just a demo project, and I don't actually have any tooling set up to minify the code as part of a build process for this one. So I could that set that up but it might be a bit of work.

But, even with minified code, I don't think that stops someone from being able to manipulate code on the client side. That's sort of a general rule of thumb for programming, any smart person can modify things on the client side of your app using the dev tools, so you need to validate everything on the server side too since you can't necessarily trust any data coming from the client.

So I wonder if there are some other clever ways we could catch cheaters.

Thoughts?

**Comment by ChipBrowne** [comment]
@Bboy111444 ^^ see question

**Comment by TheOGBuhay** [comment]
I'm no expert, but I have a few ideas that might help small cases of manipulation. Something as simple as changing variable names to something that only you would understand. I was able to manipulate my score just by simply ctrl-f "score". It's not going to completely stop the cheater, but it might make it slightly more difficult for them.

**Comment by thawkin3** [comment]
@Bboy111444 @TheOGBuhay I've implemented a couple of changes in this PR to help address some potential areas where cheating could occur, so please read the PR summary for more info. Let me know if there is anything else for this you'd like me to look into. I'm going to close the issue for now. Thanks!
https://github.com/thawkin3/crossyBlock/pull/6

**Comment by thawkin3** [comment]
@Bboy111444 @TheOGBuhay With these new changes, could you now go back and check that scoring works properly during normal game play?
